name: Generate Installer
description: 'Generates the installer for Pragma.'
inputs:
  version:
    description: 'Pragma Version.'
    required: true
  install-directory:
    description: 'Pragma installation directory'
    required: true
  deps-directory:
    description: 'Pragma deps directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Pragma
      shell: bash
      run: |
        python build_scripts/generate_installer.py --version "${{ inputs.version }}" --install-directory "${{ inputs.install-directory }}" --deps-directory "${{ inputs.deps-directory }}"
