name: Generate Installer
on:
  workflow_dispatch:

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  build:
    permissions:
      actions: write
      contents: write
      issues: read
      pull-requests: read

    name: Generate Installer - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
    steps:
      - uses: actions/checkout@v2

      - name: Create Directories
        shell: bash
        run: |
          mkdir pragma
          cd pragma
          mkdir deps
          mkdir install

      - name: Download and Extract Pragma
        run: |
          curl -L -o pragma-win64.zip https://github.com/Silverlan/pragma/releases/download/nightly/pragma-win64.zip
          unzip pragma-win64.zip -d pragma/install
          rm pragma-win64.zip

      - name: Generate Installer
        uses: Silverlan/test_pragma_installer/github_actions/generate_installer@main
        with:
          version: "1.0.0"
          install-directory: "${{ github.workspace }}/pragma/install"
          deps-directory: "${{ github.workspace }}/pragma/deps"
